# 最大页数
MaxNumberOfPages: 5
# 解锁耗费
UnLock:
  # 金币
  Vault: 500
  # 点券
  PlayerPoints: 200
# 取出物品
RemoveItems:
  # 金币
  Vault: 100
  # 点券
  PlayerPoints: 100
# 放入物品
UploadItem:
  # 金币
  Vault: 50
  # 点券
  PlayerPoints: 50
Lang:
  UploadDeductionError: "扣款失败!"
  UploadMax: "仓库已经存不下了，请扩充仓库后重新尝试！"
  PushDeductionError: "扣款失败!"
